version: "3.9"

services:
  
  # ==== Metasploitable2 Container ====
  metasploitable2:
    container_name: metasploitable
    hostname: metasploitable
    ports:
      - "8080:80"
    networks:
      pentest-net:
        ipv4_address: 10.0.0.3
    stdin_open: true 
    tty: true
    image: "tleemcjr/metasploitable2"
    
  # ==== Attacker Container ====
  security:
    container_name: parrot
    hostname: parrot
    network_mode: pentest-net
    networks:
      pentest-net:
        ipv4_address: 10.0.0.2
    volumes:
      - './attacker:/attacker'
    stdin_open: true 
    tty: true
    image: 'parrotsec/security:latest'

  # ==== FTWS, a Fully of Threat Web Site with Apache and MySQL ====
  ftws:
    container_name: ftws
    build: ./FTWS
    volumes:
      - ./FTWS/ftws:/srv/ftws
#    depends_on:
#      - db
    ports:
      - "8000:80"
    networks:
      pentest-net:
        ipv4_address: 10.0.0.4
  
  db:
    container_name: ftws_db
    image: mysql #mysql:8.4
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PenTestLab
      MYSQL_USER: dbadmin_ftws
      MYSQL_PASSWORD: FTWSLab
      MYSQL_DATABASE: ftws_db
    networks:
      pentest-net:
        ipv4_address: 10.0.0.5

  # ==== NextCloud ====
  nextcloud:
    container_name: nextcloud
    hostname: nextcloud
    networks:
      pentest-net:
        ipv4_address: 10.0.0.10
    ports:
      - "3000:80"
    image: 'nextcloud'

networks:
  pentest-net:
    name: pentest-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
