version: "3.9"

services:
  # ==== Metasploitable2 Container ====
  metasploitable2:
    container_name: metasploitable
    hostname: metasploitable
    ports:
      - "8080:80"
    networks:
      pentest-net:
        ipv4_address: 10.0.0.3
    stdin_open: true 
    tty: true
    image: "tleemcjr/metasploitable2"
  
  # ==== Custom Web App Container, with redis ====
  web:
    build: .
    ports:
      - "8000:5000"
    networks:
      pentest-net:
        ipv4_address: 10.0.0.4
  redis:
    image: "redis:alpine"
    networks:
      pentest-net:
        ipv4_address: 10.0.0.5
  
  # ==== Attacker Container ====
  security:
    container_name: parrot
    hostname: parrot
    network_mode: pentest-net
    networks:
      pentest-net:
        ipv4_address: 10.0.0.2
    volumes:
      - '$PWD/attacker:/attacker'
    stdin_open: true 
    tty: true
    image: 'parrotsec/security:latest'

networks:
  pentest-net:
    name: pentest-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
