version: "3.9"

services:
  # ==== FTWS, a Fully of Threat Web Site with Apache and MySQL ====
  ftws:
    container_name: ftws
    build: .
    volumes:
      - ./ftws:/srv/ftws
#    depends_on:
#      - db
    ports:
      - "8000:80"
  
  db:
    container_name: ftws_db
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PenTestLab
      MYSQL_USER: dbadmin_ftws
      MYSQL_PASSWORD: FTWSLab
      MYSQL_DATABASE: ftws_dbs